### ISSUE TITLE
Causes some page text with angle brackets to be hidden

### ISSUE THREAD

**Issue by halr9000** [jacksenechal/Skype-for-Chrome#8]
I just found that when this extension is enabled, I was unable to view some text on certain webpages. I narrowed it down to a quick repro:

1. enable extension
2. visit http://docs.splunk.com/Documentation/Splunk/latest/admin/Propsconf
3. search for "for a given".

The sentence near the search result should display (I've replaced angle brackets with square brackets): "This stanza enables properties for a given [spec].". What is happening is that the portion including [spec] is hidden, but only when this extension is enabled.

To validate that this is a display issue, and not server-side:
1. View source of same webpage
2. search for "for a given"
3. Note that the HTML source includes: "This stanza enables properties for a given &lt;spec&gt;."

**Comment by jacksenechal** [comment]
https://github.com/jacksenechal/Skype-for-Chrome/pull/15 seems to have fixed this. I suspect it was a bug in the jquery-replacetext library that the plugin uses. The pull request included an updated version.
